### ISSUE TITLE
[nova] live-migration block migration

### ISSUE THREAD

**Issue by pmesserli** [rcbops/chef-cookbooks#399] opened 2013-05-16 15:53 UTC
This is more of a possible enhancement to enabling the option to live migrate VM's between hosts.  When a live block migration is initiated it appears that the VM is migrating, and will show a migration status when you run a nova show (ID).  However it actually never migrates the image, although it attempts to create the VM under /var/lib/nova instances on the destination host, but deletes the directory shortly after.

It appears that the nova.conf is missing a line to enable the use of live migration.

live_migration_flag=VIR_MIGRATE_UNDEFINE_SOURCE,VIR_MIGRATE_PEER2PEER,VIR_MIGRATE_LIVE

It also appears that the vnc_listen was set to the hostIP, and needed to be changed to listen on 0.0.0.0.

cookbooks/nova/attributes/default.rb

default["nova"]["libvirt"]["vncserver_listen"] = "0.0.0.0"
default["nova"]["config"]["live_migration_flag"] = "VIR_MIGRATE_UNDEFINE_SOURCE,VIR_MIGRATE_PEER2PEER,VIR_MIGRATE_LIVE"         # node attribute

nova/templates/default/folsom/nova.conf.erb

live_migration_flag=<%= @live_migration_flag %>
live_migration_bandwidth=0
live_migration_retry_count=30

After doing the above changes we were able to successfully perform a block migration between hosts.

**Comment by breu** [comment] 2013-06-04 15:09
@pmesserli can you verify that setting just the vncserver_listen to 0.0.0.0 resolves this?  This is an upstream nova bug that needs to get resolved.

**Comment by pmesserli** [comment] 2013-06-04 15:13
Yes, along with the added live_migration_flag entries.

**Comment by JCallicoat** [comment] 2013-06-04 18:19
The VIR_MIGRATE_LIVE flag shouldn't be needed. It makes Nova use the native libvirt migration mechanism, which is prone to failure: "The Compute service does not use libvirt's live miration by default because there is a risk that the migration process will never terminate. This can happen if the guest operating system dirties blocks on the disk faster than they can migrated."[1] However, we found that Nova live migration wasn't working and used that flag as a work-around. We should figure out why Nova live migration is failing rather than switching to using the libvirt live migration, imo.

[1] http://docs.openstack.org/trunk/openstack-compute/admin/content/configuring-migrations.html

**Comment by JCallicoat** [comment] 2013-06-04 19:59
Additionally, changing that flag only allows instances to migrate that were booted _after_ the flag was set.

**Comment by mancdaz** [comment] 2013-07-12 06:34
@JCallicoat are you able to provide some logs from when migrations are failing?

**Comment by seancarlisle** [comment] 2013-07-17 21:51
In addition, we must also add the following line to nova/providers/conf.rb:

"live_migration_flag" => node["nova"]["config"]["live_migration_flag"]

**Comment by mancdaz** [comment] 2013-08-06 12:35
@JCallicoat 

Can we get some more logs from when the migrations are failing.  The cookbooks have changed quite a lot since this original issue was logged, so I wonder if the issue is still current?

Cheers
@mancdaz

**Comment by odyssey4me** [comment] 2013-08-23 09:09
The vnc_server parameter should be easily set by implementing the following in your chef environment file:

``` json
    "nova": {
      "libvirt": {
        "vncserver_listen": "0.0.0.0"
      }
```

However, it would appear that something overrides that for the compute nodes. I'll see what I can figure out.

@mancdaz I'm testing with Grizzly and haven't come across the need yet for the live_migration_flag to be set for this to work. That said, I am working with shared instance storage. :/

Something I am seeing in the logs is this:
2013-08-23 10:54:44.880 WARNING nova.virt.libvirt.utils [req-f3338e9e-dd02-4ea4-baed-c4caa58770cf fe913fa984124ea2b18313d80de499ff b8452c61ded4470c9d543ac605713187] systool is not installed

This is resolved by installing the 'sysfsutils' on Ubuntu. This needs to be included in the compute packages to install.

I'm also seeing that instances that have attached volumes can't migrate. I'll get to the bottom of both of these issues shortly.

**Comment by DavidWittman** [comment] 2013-09-03 22:29
This was the only error I received when attempting to migrate (found in nova-compute.log):

> 2013-09-03 16:08:48.399 30843 ERROR nova.virt.libvirt.driver [-] [instance: c105ef3a-070a-4330-a9a2-51ad636246e0] Live Migration failure: Unable to read from monitor: Connection reset by peer

Setting `vncserver_listen` to 0.0.0.0 fixed it. Committing some changes to at least allow us to set it in the environment per @odyssey4me's comment.

**Closed as completed** 2013-09-03 23:38 UTC
