### ISSUE TITLE
[DE122]: Cookbook compatibility with Chef 11

### ISSUE THREAD

**Issue by joeburke30** [rcbops/chef-cookbooks#382] opened 2013-04-30 19:27 UTC
Swift cookbooks do not work with Chef 11.  Need to update for compatibility

**Comment by galstrom21** [comment] 2013-04-30 19:40
@joeburke30: can you please provide more details.. our gating process has been using Chef 11.4.4 and does swift installations.

**Comment by galstrom21** [comment] 2013-04-30 19:41
@joeburke30: also can you provide which branch you are referring to? (master, sprint, stable/folsom)

**Comment by joeburke30** [comment] 2013-04-30 20:00
hmmm... I'm using Chef 11.0.4-1 with ubuntu.    I see chef 11.4 was released but it is not being pulled down via open center.   interesting.

**Comment by galstrom21** [comment] 2013-05-01 17:06
@joeburke30: so that is the version of chef-client being used by opencenter installs.. Can you please provide more details around the errors you were seeing?

**Comment by galstrom21** [comment] 2013-05-07 20:00
@joeburke30: ping

**Comment by git-harry** [comment] 2013-05-28 09:06
I'm closing this because we are unable to reproduce it. If you can provide any further details we will take another look.

**Closed as completed by git-harry** 2013-05-28 09:06 UTC
