### ISSUE TITLE
[DE218]: Error executing action `join` on resource 'dsh_group[nova]

### ISSUE THREAD

**Issue by aamirdb** [rcbops/chef-cookbooks#484] opened 2013-07-20 12:45 UTC
Hello, 

I m getting this error when running the chef-client for a single-controller node. This is  on a Ubuntu 12.04 - 
# 

[Sat, 20 Jul 2013 16:41:49 +0400] INFO: Generating ssh keys for user nova from /var/lib/nova/.ssh/id_rsa and /var/lib/nova/.ssh/id_rsa.pub
# 
# Error executing action `join` on resource 'dsh_group[nova]'
## TypeError

can't convert Hash into String
## Cookbook Trace:

/var/chef/cache/cookbooks/dsh/providers/group.rb:147:in `system'
/var/chef/cache/cookbooks/dsh/providers/group.rb:147:in`get_pubkey'
/var/chef/cache/cookbooks/dsh/providers/group.rb:84:in `class_from_file'
## Resource Declaration:
# In /var/chef/cache/cookbooks/nova/recipes/nova-common.rb

102: dsh_group "nova" do
103:   user "nova"
104:   admin_user "nova"
105:   group "nova"
106: end
## Compiled Resource:
# Declared in /var/chef/cache/cookbooks/nova/recipes/nova-common.rb:102:in `from_file'

dsh_group("nova") do
  updated true
  cookbook_name "nova"
  action :join
  user "nova"
  retry_delay 2
  updated_by_last_action true
  group "nova"
  admin_user "nova"
  recipe_name "nova-common"
  retries 0
end

[Sat, 20 Jul 2013 16:41:49 +0400] ERROR: Running exception handlers
[Sat, 20 Jul 2013 16:41:49 +0400] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[Sat, 20 Jul 2013 16:41:49 +0400] ERROR: Exception handlers complete
[Sat, 20 Jul 2013 16:41:49 +0400] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[Sat, 20 Jul 2013 16:41:49 +0400] FATAL: TypeError: dsh_group[nova](nova::nova-common line 102) had an error: TypeError: can't convert Hash into String
# 

Please do let me know if there is a fix for this.

Thanks

**Comment by git-harry** [comment] 2013-07-22 15:32
@aamirdb I was unable to reproduce this using the latest grizzly cookbooks.

Please will you confirm the cookbook branch you are using. Is it up-to-date?

What attributes have you set in your environment?

**Comment by willkelly** [comment] 2013-07-22 21:45
Hello!  I have seen similar issues when running chef with ruby 1.8 or early versions of ruby 1.9.  Can you verify the version of ruby your chef-client installation is using is 1.9.3?

**Comment by git-harry** [comment] 2013-08-13 08:16
@aamirdb I will close this issue because you haven't responded to the comments above. If you are still having trouble please update up with further information.

**Closed as completed by git-harry** 2013-08-13 08:16 UTC
