### ISSUE TITLE
Space in nova.conf.erb

### ISSUE THREAD

**Issue by xin-e-liu** [rcbops/chef-cookbooks#299] opened 2013-01-26 16:27 UTC
Hi guys, 

I think the nova.conf.erb template file is incorrect. Currently with the template, it produces a nova.conf like below:
##### NETWORK

network_manager=nova.network.manager.FlatDHCPManagermulti_host=falsepublic_interface=eth0fixed_range=1.1.1.0/24dmz_cidr=1.1.1.0/24force_dhcp_release=truesend_arp_for_ha=trueauto_assign_floating_ip=falsedhcp_domain=novalocaldhcpbridge_flagfile=/etc/nova/nova.confdhcpbridge=/usr/bin/nova-dhcpbridgelibvirt_use_virtio_for_bridges=true

This is no space and line breaks. I have modified nova.conf.erb to
##### NETWORK

<% @network_options.each do |key,value| %>
<%=key%>=<%=value %>
<% end %>

And now it generates correct nova.conf
##### NETWORK

network_manager=nova.network.manager.FlatDHCPManager
multi_host=false
public_interface=eth0
fixed_range=1.1.1.0/24
dmz_cidr=1.1.1.0/24
force_dhcp_release=true
send_arp_for_ha=true
auto_assign_floating_ip=false
dhcp_domain=novalocal
dhcpbridge_flagfile=/etc/nova/nova.conf
dhcpbridge=/usr/bin/nova-dhcpbridge
libvirt_use_virtio_for_bridges=true

Thanks,
Xin

**Comment by mancdaz** [comment] 2013-01-28 17:08
@codeoedoc

I can't reproduce this issue in my testing, and we've spun up hundreds of openstack clusters using the teplate file as is.  I suspect this is some odd local issue that you are experiencing.  Just a stab in the dark - what version of chef are you running with?

@mancdaz

**Comment by xin-e-liu** [comment] 2013-01-28 17:15
Thanks Darren.

Chef version is 10.18.2
Ruby version is 1.9.3

Just by looking at the erb file, the network section:

Original
################################
NETWORK

<% @network_options.each do |key,value| %>
<%=key%>=<%=value-%>
<% end %>
################################

Modified
################################
NETWORK

<% @network_options.each do |key,value| %>
<%=key%>=<%=value %>
<% end %>
################################

Which one do you think will produce the config file with each parameter on a separate line? The modified version works for me. 

Regards,
Xin

**Comment by mancdaz** [comment] 2013-03-21 15:49
@codeoedoc am closing this issue as we were not able to reproduce...

**Closed as completed by mancdaz** 2013-03-21 15:49 UTC
