### ISSUE TITLE
Keystone version in current cookbooks

### ISSUE THREAD

**Issue by xin-e-liu** [rcbops/chef-cookbooks#297] opened 2013-01-25 23:50 UTC
Hi guys, 

Sorry this might be a non-issue again. I didn't find a place to send questions. I'll just put it here. Later if it turns out that this is not an issue, I'll remove it. 

The problem I have is keystone version. It seems the keystone.conf is already folsom, however the source code for keystone is essex. When I install everything from a fresh start using chef-cookbooks, keystone failed complaining no module for stats. It turns out that stats is provided by keystone, and it's there contrib/stats in folsom, not in essex. 

keystone.conf:
[filter:stats_monitoring]
paste.filter_factory = keystone.contrib.stats:StatsMiddleware.factory

The source code that the cookbook pulls doesn't have this module. 

Thanks,
Xin

**Comment by xin-e-liu** [comment] 2013-01-26 01:44
I changed the package_component to "essex-final", it goes past the keystone installation. So I think there is some version discrepancy in the keystone.conf and the keystone source.

**Comment by breu** [comment] 2013-01-26 02:02
Hello,

Do you already have the folsom versions of keystone installed and the folsom repository added to the system?  Ubuntu naming scheme for packages uses the same name for folsom and essex packages so if you are installing essex but have the folsom package repositories defined then you have an unresolvable conflict that these cookbooks will not solve.

**Comment by xin-e-liu** [comment] 2013-01-26 02:05
It's a clean Ubuntu 12.04 system I just installed. So it's some naming issue with Ubuntu repository? I've reverted back to essex-final though...

**Comment by mancdaz** [comment] 2013-03-21 15:48
@codeoedoc I'm closing this issue as we could not reproduce...

**Closed as completed by mancdaz** 2013-03-21 15:48 UTC
